version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: rugram_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - rugram_postgres_data:/var/lib/postgresql/data
    networks:
      - rugram_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: rugram_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - rugram_redis_data:/data
    networks:
      - rugram_network
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', '--pass', '${REDIS_PASSWORD}', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: rugram_api
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      APP_PORT: ${APP_PORT}
      APP_ENV: ${APP_ENV}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      CACHE_TTL_DEFAULT: ${CACHE_TTL_DEFAULT}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rugram_network
    volumes:
      - ./internal/database/migrations:/root/internal/database/migrations

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rugram_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - '5050:80'
    networks:
      - rugram_network
    depends_on:
      - postgres

volumes:
  rugram_postgres_data:
  rugram_redis_data:

networks:
  rugram_network:
    driver: bridge
